### ISSUE TITLE
Disconected Websocket experienced an errorJS: Error: Websocket ws://192.168.56.1:8181 experienced an error

### ISSUE THREAD

**Issue by mattpcaswell** [triniwiz/horizon-nativescript-chat-app#1]
Hey,

I installed and ran the angular demo as it says in the readme and i got the error `JS: Error: Websocket ws://192.168.56.1:8181 experienced an error` when running the app on a genymotion android emulator. I could send one message that was never received and then the app would crash. 

I have the server running and I can go to the rethinkDB dashboard and look around, so I dont think it has anything to do with the server.

Thanks!

**Comment by mattpcaswell** [comment]
I changed the server url in the config.ts file to 10.0.3.2:8181 and it now works perfectly.

**Comment by triniwiz** [comment]
Good to hear the `192.168.56.1` ip was using genymotion
